#!/bin/bash
#
# xmonad startup script. Intended to be run from an xsession configuration
# to run xmonad and some associated programs.
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# KLUDGES AND WORKAROUNDS
#

# Clear xmonad.state before starting xmonad -- otherwise this causes weird
# issues, especially when going between single screen and multi-screen
rm -f ~/.xmonad/xmonad.state

#
# GENERAL INITIALIZATION
#

# Identify the home of our gtkrc file, important for setting styles of
# gtk-based applications
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Load X resources (fixes some font issues)
xrdb -merge .Xresources

# Start compositing to support transparency. You can omit this
# if you prefer not to use any transparency, but it is likely to cause
# ugly black fringing with some programs such as synapse that expect
# transparency support.
xcompmgr -n &

#
# SCREEN CONFIGURATION
#

# We handle our screen configuration using xrandr. You are likely to want to
# edit this section to match the specific demands of your setup. The below
# setup is for a Lenovo W520 laptop that sometimes has an external monitor
# hooked up via either VGA or DVI, positioned to the left of the laptop.
#
# Note that you can run xrandr at the command line to get a list of your
# connected screens and find out what names you should use to refer to them.

# Activate primary screen
xrandr --output eDP-1 --auto --primary

# If we find that a screen is connected via Display Port, activate it and position it
# to the left of the primary screen.
xrandr | grep 'DP-1 connected' | ifne xrandr --output DP-1 --auto --right-of eDP-1

# If we find a screen connected via Display Port, make it the primary screen
# and deactivate the built-in screen... also adjust size of icons
#DP_1_CONNECTED=`xrandr | grep 'DP-1 connected'`
#if [ -n "$DP_1_CONNECTED" ]; then
#  xrandr --output LVDS-1-1 --off
#  xrandr --output DP-1 --auto --primary
#  STALONETRAY_SLOT_SIZE=29
#fi

#
# LOAD SCREEN BACKGROUNDS
#

emacs --daemon &

#
# STARTUP ICON TRAY
#

trayer \
    --monitor primary \
    --edge top \
    --align right \
    --expand true \
    --widthtype request \
    --heighttype pixel \
    --height 34 \
    --padding 3 \
    --tint 0x2b2b2b \
    --alpha 0 \
    --transparent true \
&

# Run the gnome-keyring-daemon to avoid issues you otherwise may encounter
# when using gnome applications which expect access to the keyring, such
# as Empathy. This prevents prompts you may otherwise get for invalid
# certificates and the like.
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

# Change the default X cursor away from the "X"
xsetroot -cursor_name left_ptr

# Now, finally, start xmonad
exec xmonad
